######################################################################
# Automatically generated by qmake (2.01a) Mon May 7 16:16:12 2012
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT -= app_bundle
QT -= gui
CONFIG -= app_bundle

# Input
HEADERS += ../Equip.h \
           TestEquip.moc \
           ../EquipReaderFactory.h \
           ../EquipReader.h \
           ../EquipReaderTxt.h
SOURCES += TestEquip.cpp \
           TestReaders.cpp \
           ../Equip.cpp \
           ../EquipReaderFactory.cpp \
           ../EquipReader.cpp \
           ../EquipReaderTxt.cpp
