######################################################################
# Automatically generated by qmake (2.01a) Sun May 6 18:33:04 2012
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

mac {
    CONFIG -= app_bundle
}

# Input
HEADERS += ../Equip.h
SOURCES += TestEquip.cpp ../Equip.cpp
