######################################################################
# Automatically generated by qmake (2.01a) Mon May 7 20:58:38 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT -= gui
QT += testlib
CONFIG -= app_bundle
CONFIG += debug

# Input
HEADERS += ../Equip.h \
           ../EquipReaderFactory.h \
           ../EquipReader.h \
           ../EquipReaderTxt.h
SOURCES += TestEquip.cpp \
           TestReaders.cpp \
           ../Equip.cpp \
           ../EquipReaderFactory.cpp \
           ../EquipReader.cpp \
           ../EquipReaderTxt.cpp
