/*
equipmant.h

Equipmant V2.0 Copyright (C) 2007 Gregory McQuillan <gmcquillan@gmail.com>
Equipmant comes with ABSOLUTELY NO WARRANTY; for details see the included text file LICENSE
This is free software, and you are welcome to redistribute it
under certain conditions; see LICENSE for more information.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

#ifndef __EQUIPMANT_H
#define __EQUIPMANT_H

#define EQM_VERSION "4.0b"

#define COMMENT strOut << "//";

//NOTE: CHANGING EQM_EXTRADATA /WILL/ CAUSE COMPATIBILITY ISSUES WITH FILES
//        GENERATED FROM OLDER VERSIONS OF EQUIPMANT. KEEP THIS IN MIND.

//...just kidding! -GM 2012
#define EQM_EXTRADATA "//Extra data found in file:\n"

#define EQM_OPC1 "//Equipmant Script File (Generated by Equipmant V" << EQM_VERSION << ")\n"
#define EQM_OPC2 "//Get your copy at: http://equipmant.sourceforge.net\n" << "\r\n" 

#endif
