######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 17 16:44:50 2007
######################################################################

TEMPLATE = app
TARGET = equip
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += equipmant.h imp_about.h imp_equipmant.h
FORMS += about.ui equipmant.ui
SOURCES += imp_about.cpp imp_equipmant.cpp main.cpp
RESOURCES += equip.qrc
ICON = equip.icns
RC_FILE = equip.rc
